### ISSUE TITLE
Craft\GiftVoucher_VoucherModel throws errors on checkout.

### ISSUE THREAD

**Issue by tokersey** [verbb/gift-voucher#1]
Hello,

I just installed the plugin locally to see if this will fit out needs for an upcoming project. However, I did find a couple of issues after adding a gift voucher to a cart and visiting the cart page. On the cart page, the following error appears:

`Craft\GiftVoucher_VoucherModel and its behaviors do not have a method or closure named "variants".`

If I add a "variant" item to the definedAttributes() in the model, then another appears:

`Craft\GiftVoucher_VoucherModel and its behaviors do not have a method or closure named "unlimitedStock".`

And finally, adding in the unlimitedStock then another appears.

`Craft\GiftVoucher_VoucherModel and its behaviors do not have a method or closure named "stock".`

I think the GiftVoucher_VoucherModel just needs these added to solve the problem, but I am not sure if that is a permanent solution. The site is still Craft 2 so may be part of the issue.

Thanks,

Todd Kersey

**Comment by engram-design** [comment]
I think the issue here is that your templating likely needs to be updated to handle Gift Vouchers. Vouchers don't have attributes like variants, unlimitedStock and stock, because they're not products or variants. I can see we don't specifically have an example for the cart page in the docs, so I can see why this might be a stumbling point.

You'll want to add a conditional to your cart page, when looping through your line items. Something like:

```
{% for item in order.lineItems %}
    {% if craft.giftVoucher.isVoucher(item) %}
        // Output Gift Voucher
    {% else %}
        // Output regular product
    {% endif %}
{% endif %}
```

Having said that, we're not against adding these attributes to suppress these errors so things are a littl easier to deal with.

**Comment by tokersey** [comment]
Yes, that does appear to be the issue. Thanks for pointing out the .isVoucher option. We will just have to go through and add a check throughout the store to ensure the pages are looking at the correct purchasable item.
