### ISSUE TITLE
Gift voucher that is above total cart amount not fully applying?

### ISSUE THREAD

**Issue by robzor** [verbb/gift-voucher#111]
### Question

HI there, 

I'm not sure if this is a bug in Commerce or Gift Voucher or just a Commerce configuration issue but I have a gift voucher of £500 applied to this basket:

![CleanShot 2023-01-27 at 5 11 38](https://user-images.githubusercontent.com/704032/215150966-4086d544-5834-4b6b-9762-34cf2c09c277.png)

As you can see, the order total is £80 instead of £0. 

Am I missing something obvious here?

In my `gift-voucher.php` I have `'registerAdjuster' => 'afterTax',` but it shows as £80 even with beforeTax in there.

Thanks!

**Comment by engram-design** [comment]
What version of Craft, Commerce and Gift Voucher are you on? This should have been filed as a bug report so I can investigate.

Looks like it's taking the value off the voucher correctly, but it's not taking the shipping amount off the cart total, which is strange.

**Comment by robzor** [comment]
Hi there, I'm on the latest version of everything in Craft 4.

I wasn't sure if it was a bug or a configuration issue.

**Comment by robzor** [comment]
Would it help if i delete this and resubmit as a bug?

Versions for clarification:

Craft Pro 4.3.6.1
Commerce 4.2.4
Gift Voucher 3.0.6

**Comment by engram-design** [comment]
That's okay, just needed the right versions to proceed. I'll take a look into this.

Out of interest, is this an order/cart created from the front-end, or from the control panel? Are you also able to send through your shipping configuration so I can replicate your setup?

**Comment by robzor** [comment]
This was an order created from the front-end but I am still developing the gift voucher stuff so it is possible that this is to do with that, I think this is why I didn't originally choose bug and rather question.

I know with Discounts (which I am implementing at the same time) they are not applied to the shipping, which the client is happy with, but this is a weird one where it is removing the VAT from the shipping (the shipping cost is £96 inc. VAT) but not the shipping cost itself. 

We have quite of lot of shipping rules, is there an easy way I can send you our config for that? It's not stored in project config afaik.

Happy to give you whatever you need to debug it though!

**Comment by robzor** [comment]
FWIW, I have just updated Craft Commerce to 4.2.5

**Comment by engram-design** [comment]
So the gift voucher adjuster sits after all other adjusters (tax, shipping, discount)  unless you use the `registerAdjuster` plugin setting. It's also its own category of adjuster so it shouldn't interfere with discounts.

Best to send through your `commerce_shipping*` database tables (there are a few) and I'll see if that can help.

**Comment by robzor** [comment]
Hi there,

attached are the shipping* tables. I hope this helps!

Thanks for looking into this, it really is a fantastic plugin :)

[cvt-shippingrules-local-backup-02-02-2023.sql.gz](https://github.com/verbb/gift-voucher/files/10567421/cvt-shippingrules-local-backup-02-02-2023.sql.gz)

**Comment by engram-design** [comment]
Thanks for sending that through, unfortunately still not able to reproduce things without the entire picture of your site setup (taxes, shipping origin/destination, products, voucher settings), so I'm wondering if it'd be possible to get a copy of your database? Understand if you can't send that through, but if you can, send to `support@verbb.io` and hopefully that'll get me a step closer to replicating your setup.

For example, a $50 product, with $80 shipping and a $200 voucher calculates correctly.

<img width="1049" alt="image" src="https://user-images.githubusercontent.com/1221575/217681551-297312e1-a957-4cfb-8f43-aa4e1b494772.png">

**Comment by robzor** [comment]
Hi there,

I just did another full test (purchasing a voucher, then applying it to an order with a value under the voucher amount) to make sure it wasn't just an issue I had while building and the issue is still there:

![CleanShot 2023-02-09 at 10 30 17](https://user-images.githubusercontent.com/704032/217787509-4ded89a2-e80c-46f4-8c0c-e54cc1e4745f.png)

I've sent you a copy of the database with our `gift-voucher.php` config settings. Let me know if you need any more info or would like to login to the staging environment. 

Thank you for your help on this, we're eager to get the feature live in the next week orso and the client is very happy with the plugin :)

As an aside, with Commerce Discounts they don't apply to the shipping cost, perhaps there could be a config option in the future with Gift Vouchers that they don't apply to shipping costs?

**Comment by engram-design** [comment]
Thanks, I'll take a look! Unfortunately, that may not ever be possible, because it's logic in the Shipping adjuster with Commerce that checks for the presence of any currently-applied discount, and if that discount should _not_ be applied to shipping. Because a gift voucher code is no longer a discount adjuster (it used to be), there's no current way to work that check into Commerce's shipping adjuster.

Maybe we'll figure something out one day!

**Comment by engram-design** [comment]
Okay, so it's due to this Commerce setting.

<img width="670" alt="image" src="https://user-images.githubusercontent.com/1221575/218056763-c1bc58c8-e8b7-48ff-8de5-38d85cdf4985.png">

This is semi-new setting for Commerce, so I wasn't really aware of it. But this setting will return the largest amount of the order total, and the shipping total. The order total being $0 and the shipping being $80 So it's working as expected!

**Comment by robzor** [comment]
Ahhhhh! 

Thank you for finding this! 

Is it still a bug that £100 is being taken off the gift voucher though, instead of £11.09? 

It's also interesting that the voucher is subtracting the £16 VAT for the shipping (Shipping is actually £96 inc. VAT), is that because of the `afterTax` setting I have in the config?

**Comment by robzor** [comment]
I've just done a test and changed that to Default and it worked perfectly. I'm not sure why you would choose 'Zero' vs 'Default' though.

**Comment by engram-design** [comment]
Well, it's a weird thing where it's actually factoring in the shipping + cart content **but** it overrides all that at the end to  set the order total to be £80 no matter what. I'm not sure if that's a but or anything, but I imagine the same thing happens for a discount that would zero-out a cart. So yeah, you end up with the odd situation that it's taking off the amount, but you still have to pay shipping due to that setting. From what I can tell, not much we can do about that.

Taxed shipping is a little tricky, but using `afterTax` should handle it - which is the default I believe. Some people in the UK like to not have VAT on shipping covered in a voucher redemption.

**Comment by robzor** [comment]
I've just been doing some reading, it seems that with a Commerce Discount you can make the total price go into the negative and so they added this setting to try and alleviate it. Thank you so much for finding the issue though! I owe you a beer :)

**Comment by engram-design** [comment]
Yeah fair enough. Good to know if this crops up again!
