### ISSUE TITLE
Voucher PDF Filename Format for Bulk Generated Vouchers (no order)

### ISSUE THREAD

**Issue by andreapasotti** [verbb/gift-voucher#121]
### Question

I've a bunch of bulk generated vouchers. How can I set a variable, such as "codeKey" to append to the PDF filename?

I tried everything I could think of, such as:

- Voucher-{codeKey}
- Voucher-{voucher.codeKey}
- Voucher-{id}
- ...

But without any luck. And I can't find anything on the documentation.

Is it possibile to have a different variable if no orderId is linked to a voucher?

Thank You!

**Comment by engram-design** [comment]
At the moment, the only variables that can be used in the `voucherCodesPdfFilenameFormat` setting are from the order. The issue with using the `codeKey` is that there can be multiple codes in a PDF, so that won't work. Similarly for ID - what are you expecting that to be - the ID of a voucher, or a code?

Currently, if you don't provide a `voucherCodesPdfFilenameFormat` value, it'll use a `Voucher-{orderNumber}` if there's a Commerce order associated with the voucher purchase, or use the first code's key `Voucher-GHWVBD` for example.

Having _said_ that, I've realised that the `voucherCodesPdfFilenameFormat` is actually required, so it can't be "empty" for our fallback. As such, I've added `codeKey` as a variable to use, which will be the first code's `codeKey`.

Added for the next release. To get this early, run `composer require verbb/gift-voucher:"dev-craft-4 as 3.0.9"`.

Hope that helps!

**Comment by andreapasotti** [comment]
Thank You very much Josh, I'm testing this right now!

**Comment by andreapasotti** [comment]
I've tried both ways (with "codeKey" and without any "voucherCodesPdfFilenameFormat" at all), but neither works.

I think you should change, in DownloadController.php, the "$code" var on lines 63 and 70: it should be "$codes".

`$order = $codes[0]->order;`

and 

`$fileName = 'Voucher-' . $codes[0]->codeKey;`

I'm sorry but right now I can't help you with a PR. Hope this helps anyways.

**Comment by engram-design** [comment]
Ah, good catch. To get this early, run `composer require verbb/gift-voucher:"dev-craft-4 as 3.0.9"`.

**Comment by engram-design** [comment]
Fixed in [3.0.10](https://github.com/verbb/gift-voucher/releases/tag/3.0.10)
