### ISSUE TITLE
Nothing deducted when using an offsite gateway

### ISSUE THREAD

**Issue by Tam** [verbb/gift-voucher#20]
### Description
Nothing is deducted from a gift card if and offsite gateway is used, but the discount is still applied. We have only seen / tested it when the amount discounted is less than the total amount, so payment is still required.

### Steps to reproduce

1. Create a voucher code
2. Use it on an order that is more than the amount on the voucher
3. Pay via an offsite gateway (we tested with SagePay)
4. Check the remaining amount on the voucher (should be zero)

### Additional info

- Plugin version: 2.0.11
- Craft version: Pro 3.1.30
- Commerce Version: 2.1.7
- SagePay Gateway Version: 2.0.0

**Comment by alexjcollins** [comment]
Wondering if there's been any investigation in to this one? Our client is having to manually adjust the voucher values when an order this issue affects comes in - which isn't ideal. Cheers!

**Comment by alexjcollins** [comment]
Hey, @engram-design has any progress been made on this? Could do with a fix or at least point us in the right direction to patch it until an official fix is posted. Thanks in advance!

**Comment by engram-design** [comment]
@alexjcollins Sorry for the delay, I'll get an offsite gateway setup - although I'm very surprised why it would be different. The deduction is made on the "order complete" event, which happens when an order is marked as complete (usually, also paid) Are you also using SagePay?

**Comment by alexjcollins** [comment]
No worries – thanks for getting back to me. We assumed that too; it *should* by all accounts just work.
I work with @Tam so yeah SagePay. 👍

**Comment by engram-design** [comment]
I've tried many, many times to replicate this, but just haven't been able to. I've tested with PayPal, SagePay and Mollie.

There has been several changes over the course of a year, so if you're still having issues, just let me know. If anyone experiences this, I'd advise to check the `giftvoucher_redemptions` table, to see if there is a redemption recorded.

Closing for now due to age.

**Comment by engram-design** [comment]
Well, I think I've finally figured out the issue. It's to do with how we save currently-applied codes against an order using sessions. Because we navigate from the site to the offsite gateway, we lose the session.

Instead, we can swap out the session-saving for storing codes on an order, and use a custom field (detailed in https://github.com/verbb/gift-voucher/issues/94#issuecomment-1235979536)
