### ISSUE TITLE
Apply voucher code from CP order page

### ISSUE THREAD

**Issue by jmauzyk** [verbb/gift-voucher#28]
Would be really great if there were some way to apply voucher codes from the control panel order page. This way if a user starts an order online but needs to complete over the phone (due to questions etc.), a customer service agent could apply the voucher code from the order page.

**Comment by engram-design** [comment]
Thanks to @Anubarak for his work in getting this started.

@Anubarak I can't seem to get this to work. I should be able to create a "Gift Voucher Code" field, add it to the Order Fields, then select an active cart, select an existing voucher code, and hit save. This doesn't seem to apply the coupon to the order? From what I can tell with your PR code, you'd have to edit the plugin setting for code storage to switch from `session` to `order`?

Let me know if I'm on the wrong track here.

**Comment by Anubarak** [comment]
Sorry, I should have posted an example here.

You need to set those config settings 

```php
use verbb\giftvoucher\storage\Order;

return [
    'codeStorage' => ['class' => Order::class, 'fieldHandle' => 'codes']
];
```

I use a field with the handle `codes`. Codes are then stored in the orders field layout in this field. Your adjuster will then grab all codes in this field instead of the session. It works for me in production quite well. https://github.com/Anubarak/gift-voucher/blob/craft-3/src/storage/Order.php

**Comment by cliveportman** [comment]
Is this issue referring to orders created or completed using the Commerce Admin Orders plugin by KuriousAgency?

**Comment by engram-design** [comment]
@cliveportman Nope, this would be unrelated to that plugin

**Comment by Anubarak** [comment]
@cliveportman It's just about applying Codes in the CP. Imagine the following scenario: you have a customer that's (for whatever reason) not able to proceed their payment or has trouble inserting the data or whatever the issue may be. So they call you via phone and tell you to proceed the order for you in the CP or you impersionate your session. Before this update all Codes would be "lost" because they were only in their session but not in yours.

When you change the CodeStorage to store Codes in the field layout of the order you'll be able to keep them and apply them in the CP - however there are no hints like "Voucher has no amount left" yet. Maybe that could be done later on.

@engram-design Thank you very much for merging it :) I hope you get used to my code

**Comment by cliveportman** [comment]
I think all this has been added within 2.2.0 but can I check whether you need to manually create a code field and add it to the Order fields layout? Or is this handled by the plugin on installation/update?

And when @jmauzyk created this issue - what is meant by the CP order page? I'm only aware of being able to create orders in the backend using the Commerce Admin Orders plugin. Is there another way? In Commerce 2, that is. I understand this is coming to Commerce 3.

**Comment by engram-design** [comment]
I think the original request is a bit more complicated, and while it can be achieved with some effort with @Anubarak's PR, its still not a perfect solution. The original request was to **apply** the voucher code on an order in the control panel. Full support for this will only be for Commerce 3.

We likely won't be including support for the Admin Orders plugin.

So - stay tuned!

**Comment by Anubarak** [comment]
@cliveportman you need to manually create a code field and attach it to the layout. After plugin config changes codes will be stored in that field. That means you can go to the order detail page and include codes via cp that will be applied to the order.

Not sure why this doesn't close the issue to be honest

**Comment by engram-design** [comment]
So it's been a little while since this was first opened, and Commerce 3 has arrived. Commerce 3 unfortunately has changed their order edit screen to be Vue-based, so it makes it really difficult (impossible) for us to hook into their edit functionality to provide voucher-applying.

But, I've wanted to implement this for some time. [2.5.3](https://github.com/verbb/gift-voucher/releases/tag/2.5.3) adds an option in the settings dropdown when editing an incomplete order, where you can apply a voucher code on an order from the control panel.

**Comment by Anubarak** [comment]
@engram-design it does not effect me, since I already have the feature in my project for years, but you can still hook into the order edit page and include custom html and use events to apply the code.
