### ISSUE TITLE
Voucher-discount  is not spread over all line items 

### ISSUE THREAD

**Issue by SandraSundqvist** [verbb/gift-voucher#70]
**Description**
Hi! 

I've been testing out the Gift Voucher-plugin a bit and it seems to have the functionality that we are looking for. But, I noticed that in your release notes for version 2.6.0 you wrote that: _"Discounts are now spread over all line items, when applying a voucher code. This is inline with Craft Commerce's discount adjusters are handled."_ . 

From what I can see this doesn't seem to be the case though? When I'm adding a voucher code to an order, the voucher-discount is being added to the whole order/order total, not spread over line items until the voucher-amount is used up (as it would work with a discount-code from commerce). 

**Steps to reproduce**
1. Add items to the cart 
2. Add a valid voucher-code (redeem it)
3. Look at the order under active carts (in commerce)  

**Additional info**
- Plugin version: 2.6.1
- Craft version: 3.7.13
- Craft commerce version: 3.4.2

Am I missing some setting or is this a bug? 

Best regards

**Comment by engram-design** [comment]
Yep, that line in the changelog is actually incorrect (I'll remove it). It was originally the case, when we were using the `discount` adjuster type, but that was since changed in https://github.com/verbb/gift-voucher/commit/37c56ec5d80b7f2e48a76d0366209d1385fec4f4 to use a `voucher` custom adjuster type as described in https://github.com/verbb/gift-voucher/issues/69#issuecomment-894791392

So the discount will be at the order level, which is inline with how the discount behaviour has already worked, and makes the most sense to users. There's little point breaking it down over line items, especially if we also want to apply the discount to shipping adjusters.

**Comment by SandraSundqvist** [comment]
Aah I see! Thank you very much for the clarification!

**Comment by engram-design** [comment]
Vouchers have been revamped in [2.7.0](https://github.com/verbb/gift-voucher/releases/tag/2.7.0) (again), and use a custom `voucher` adjuster. You'll no longer get the behaviour of spreading the voucher over line items, because that's how a discount adjuster works. So this should be working as expected now (not spreading over line items).
