### ISSUE TITLE
Saving an order via PHP removes gift voucher

### ISSUE THREAD

**Issue by iamkeir** [verbb/gift-voucher#95]
### Describe the bug

We have some custom module code that saves an order using the following:
`Craft::$app->getElements()->saveElement($order)`

However, when the above code is run, it seems to remove any gift voucher code applied to the order. See here:
https://user-images.githubusercontent.com/539615/193036501-c3c10514-a357-4787-b2e1-7abdb20dbf71.mov

Any ideas why that might be, and how to prevent it?

### Steps to reproduce

1. Create an order
2. Apply a voucher
3. Run `Craft::$app->getElements()->saveElement($order)`
4. Notice the voucher is removed

### Craft CMS version

Craft Pro 3.7.55.2

### Plugin version

2.7.2

### Multi-site?

No

**Comment by engram-design** [comment]
This either has to do with the recalculation mode set on the order (it's recalculating the adjusters - which a voucher is), or it's to do with the session no longer existing.

When a voucher code is applied to an order, it's saved against the order in a session. This is so that until the order is complete, we know that a voucher has been "applied" to an order. There are some edge-cases to this, like for offsite gateways which redirect away from your site, and loose the session.

One thing to try, is swapping the mechanism from session-based code storage to order-based. Instead of using sessions, it uses a custom field to keep track of applied voucher codes.

There's a bit of a guide [here](https://github.com/verbb/gift-voucher/issues/94#issuecomment-1235979536)

**Comment by iamkeir** [comment]
Fantastic insight, thank you. I will investigate and report back.

**Comment by iamkeir** [comment]
@engram-design that worked, thanks a lot Josh!
